import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading, error } = trpc.list.getList.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading && "Loading.."}
      {data ? JSON.stringify(data) : JSON.stringify(error)}
    </>
  );
};

export default Home;
