import { Todos } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [name, setName] = useState<Todos["name"]>("");

  const ctx = trpc.useContext();
  const mutation = trpc.todos.addTodo.useMutation({
    onSuccess: () => {
      ctx.todos.list.invalidate();
    },
  });
  const todos = trpc.todos.list.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        className="m-4 border-2 border-black p-2"
        type="text"
        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
          setName(e.target.value)
        }
      />
      {name}
      <button
        onClick={() => {
          mutation.mutate({ name });
        }}
      >
        Gönder
      </button>
      <div>
        <ul>
          {todos.data?.todos.map((todo) => (
            <li key={todo.id}>{todo.name}</li>
          ))}
        </ul>
      </div>
    </>
  );
};

export default Home;
